#cloud-config

# Set default user
users:
  - name: jh
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYXiwRMP0Z9DS8eix/a7EclAkGwlxagNzfE0bjLElXE hergemoeller@b1-systems.de


# Update and install packages
package_update: true
package_upgrade: true
packages:
  - git
  - curl
  - htop
  - zsh
  - python3
  - neovim
# Write a custom file
write_files:
  - path: /etc/motd
    content: |
      Welcome to your custom instance!
# Run commands on first boot
runcmd:
  - echo "Setting up custom configurations..."
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable docker.service
  - systemctl start docker.service
  - usermod -aG docker jh
  - curl -sSL https://raw.githubusercontent.com/mbecker20/komodo/main/scripts/setup-periphery.py | python3
# Configure SSH
ssh_pwauth: false
disable_root: true

# Final message
final_message: "The system is ready. Login with your configured user."

